---

collections:
  - name: community.general
    source: https://galaxy.ansible.com
    
  - name: servicenow.servicenow
    source: https://galaxy.ansible.com
  # - name: awx.awx
  # - name: ansible.windows
  #- name: ansible.posix
  #- name: azure.azcollection
  #- name: community.general
  #- name: vmware.vmware_rest
  #- name: cisco.ios
  #- name: cisco.ise
  #- name: cloud.terraform
