---

collections:
  - name: community.general
  # - name: ansible.posix
  # - name: kubernetes.core
  # - name: servicenow.itsm
  # - name: community.general

  # - name: https://github.com/ansible/galaxy_collection.git
  #   type: git

  # - name: https://github.com/ansible-collections/ansible_hub.git
  #   type: git
  # # - name: awx.awx
  # # - name: ansible.windows
  # #- name: ansible.posix
  # #- name: azure.azcollection
  # #- name: community.general
  # #- name: vmware.vmware_rest
  # #- name: cisco.ios
  # #- name: cisco.ise
  # #- name: cloud.terraform
