---

- name: Download Large JSON File
  hosts: all
  become: false
  gather_facts: false
  
  tasks:
    - name: Make tempfile
      ansible.builtin.tempfile:
        state: file
      register: temp
      
    - name: Download large json file onto server
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json
        dest: "{{ temp.path }}"
      register: download
      
    - name: Debug download
      ansible.builtin.debug: var=download
    
    - name: Output file
      ansible.builtin.command: cat "{{ temp.path }}"
      register: output
    
    - name: Debug output
      ansible.builtin.debug: var=output
      
    - name: Delete file
      ansible.builtin.file:
        path: "{{ temp.path }}"
        state: absent
