---

- name: Facts 2
  hosts: all
  gather_facts: true
  become: false
  
  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
    
    - name: Print ansible_local
      ansible.builtin.debug:
        var: ansible_local
