---

- name: Fail host and re-add them in an always block
  hosts: all
  tasks:
    - block:
        - fail:
          when: inventory_hostname == "controller1.local"
      always:
        - ping:
      
    - name: tasks
      when: inventory_hostname in groups['test_group']
      block:
        - debug: msg="hello {{ inventory_hostname }}"
