---

- name: Hello World Playbook
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  remote_user: login_user
  tasks:
    - name: Print Hello World
      ansible.builtin.debug: msg="Hello World"
