---

- name: Long Playbook
  hosts: all
  become: false
  
  tasks:
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - ansible.builtin.command: sleep 5s
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - ansible.builtin.command: sleep 5s
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - name: Task
      ansible.builtin.debug: msg="Hello World"
    - ansible.builtin.command: sleep 5s
    - ansible.builtin.command: whoami
