---

- name: Example Playbook
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Ping server
      ansible.builtin.ping:

    - name: Add public ssh key to server
      ansible.posix.authorized_key:
        user: awx
        state: present
        key: https://github.com/demonpig.keys
      
