---

- name: Synchronize Playbook
  hosts: all
  tasks:
    - ansible.builtin.file:
        path: /tmp/{{ item }}
        state: directory
      loop:
        - a
        - b
        
    - ansible.builtin.file:
        path: /tmp/a/{{ item }}
        state: touch
      loop:
        - 1
        - 2
        - 3
    
    - ansible.posix.synchronize:
        src: /tmp/a
        dest: /tmp/b
        delete: true
        checksum: true
      delegate_to: "{{ inventory_hostname }}"
