---

- name: URI Playbook
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - block:
      - name: Run a sleep command before doing anything else
        ansible.builtin.shell: sleep 9999s
        async: 9999
        poll: 0
        register: sleep_cmd

      - name: Make a call out to an API endpoint
        ansible.builtin.uri:
          url: https://catfact.ninja/facts
          return_content: true
        register: cat_facts

      - name: Check on sleep command
        ansible.builtin.async_status:
          jid: "{{ sleep_cmd.ansible_job_id }}"
        register: job_result
        until: job_result.finished
        retries: 30
        delay: 10
      delegate_to: localhost
      
    
      
      
        
