---
version: 3

dependencies:
  galaxy: []
  python: []
  system: []

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

additional_build_files: []

additional_build_steps: {}