---

- name: Hello Events
  hosts: all
  
  sources:
    - name: test
      ansible.eda.event_stream:
        name: TEST

  rules:
    - name: print all events
      condition: true
      actions:
        - print_event:
            pretty: true

    - name: Hello Condition 2
      condition: >
        event.body is defined and
        event.body[1] is defined and
        event.body[1].jobId is defined and
        event.body[1].interfaceName is defined
      action:
        run_job_template:
          name: Ping
          organization: Default
