---

- name: Hello Events
  hosts: all
  
  sources:
    - name: test
      ansible.eda.event_stream:
        name: TEST

  rules:
    - name: Keepalive Action
      condition: event.payload.message == "KEEPALIVE"
      action:
        debug:
          msg:
            - Keepalive payload received

    - name: Hello Condition 2
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default
