---

- name: Hello Events
  hosts: all
  
  sources:
    - name: test
      ansible.eda.event_stream:
        name: TEST

  rules:
    - name: TAIIA - Backend Statements
      condition: event.payload.message == "KEEPALIVE"
      actions:
        - debug:
            msg: Keepalive payload received
        - halt:

    - name: Hello Condition 2
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default
