---

- name: Hello Events
  hosts: all
  
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 1023

  rules:
    - name: Hello Condition
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default
