---

- name: Hello Events
  hosts: all
  
  sources:
    - name: test
      ansible.eda.event_stream:
        name: TEST

  rules:
    - name: Capture event data
      condition: event.payload is defined
      action:
        set_fact:
          fact:
            body: "{{ event.payload['body'] | default([]) }}"

    - name: Hello Condition 2
      condition: >
        facts.body is defined and
        facts.body[1] is defined and
        facts.body[1].jobId is defined and
        facts.body[1].interfaceName is defined
      action:
        run_job_template:
          name: Ping
          organization: Default
