---

- name: Hello Events
  hosts: all
  
  sources:
    #- ansible.eda.webhook:
    #    host: 0.0.0.0
    #    port: 9091
    - name: test
      ansible.eda.event_stream:
        name: TEST
        
  rules:
    - name: Hello Condition
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default

    - name: Hello Condition 2
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default

