---

- name: AWS SQS Test
  hosts: all

  sources:
    - ansible.eda.aws_sqs_queue:
        name: "{{ queue_name }}"
        endpoint_url: "{{ queue_endpoint }}"
        region: us-east-1
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"

  rules:
    - name: Run Ping
      condition: |
        event.body is not defined
      action:
        run_job_template:
          name: Long
          organization: Default
