---

- name: AWS SQS Test
  hosts: all

  sources:
    - ansible.eda.aws_sqs_queue:
        name: "{{ queue_name }}"
        endpoint_url: "{{ queue_endpoint }}"
        region: us-east-1

  rules:
    - name: Run Ping
      condition: |
        event.body is defined
      action:
        run_job_template:
          name: Ping
          organization: Default
