---

- name: Hello Events
  hosts: all
  
  sources:
    - ansible.eda.url_check:
        urls: "{{ urls | list }}"
        delay: "{{ delay | default(1) }}"
        verify_ssl: "{{ verify_ssl | default(False) }}"

  rules:
    - name: Hello Condition
      condition: event.payload.message == "hello"
      action:
        run_job_template:
          name: Ping
          organization: Default
