---

- name: Hello Variable Rulebook
  hosts: all

  sources:
    - name: test
      ansible.eda.event_stream:
        name: TEST

  rules:
    - name: Hello test
      condition: >
        service_name is defined and
        service_name == 'hello'
      actions:
        - print_event:
            pretty: true
