---

- name: Website Monitoring
  hosts: all

  sources:
    - ansible.eda.url_check:
        delay: "{{ delay }}"
        urls:
          - "{{ url }}"

  rules:
    - name: Website is up
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: Ping Website
          organization: Default

    - name: Website is not up
      condition: event.url_check.status == "down"
      action:
        run_playbook:
          name: playbooks/ping.yml
