---

- name: Website Monitoring
  hosts: all

  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: "{{ delay }}"
        urls:
          - "{{ url }}"

  rules:
    - name: Website is up
      condition: event.url_check.status == "up"
      throttle:
        once_after: 1 minutes
        group_by_attributes:
          - event.url_check.status
      action:
        print_event:

    - name: Website is not up
      condition: event.url_check.status == "down"
      throttle:
        once_after: 1 minutes
        group_by_attributes:
          - event.url_check.status
      action:
        print_event:
