---

- name: Playbook with a large number of AD objects
  hosts: all
  gather_facts: "{{ gather_facts | default(False) }}"

  vars:
    user_groups: []

  tasks:
    - name: Generate command
      ansible.builtin.set_fact:
        command: "python3 {{ playbook_dir }}/main.py"

    - name: Get ActiveDirectory data
      ansible.builtin.set_fact:
        user_check_mode_output_1:
          objects: "{{ lookup('ansible.builtin.pipe', command) | from_json }}"

    - name: Show data
      ansible.builtin.debug:
        var: user_check_mode_output_1

    - name: Massage data into large list
      loop: "{{ user_check_mode_output_1.objects }}"
      ansible.builtin.set_fact:
        user_groups: "{{ user_groups + [{'user_distinguished_name': item.DistinguishedName, 'user_city': item.l, 'user_upn': item.userPrincipalName}] }}"

    - name: Display users in group
      ansible.builtin.debug:
        var: user_groups

    - name: Display group size
      ansible.builtin.debug:
        msg: "{{ user_groups | length }}"
