---

- name: Testing playbook for create token
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a new token using username/password
      ansible.controller.token:
        description: Temp token
        scope: read
        state: present
        controller_username: "{{ api_username }}"
        controller_password: "{{ api_password }}"
        controller_host: "{{ tower_host | default('http://127.0.0.1') }}"
        validate_certs: false

    - name: Debug token
      ansible.builtin.debug:
        var: controller_token
        verbosity: 3

    - name: List running jobs
      register: testing_jobs
      when: ansible_facts['controller_token'] is defined and
            ansible_facts['controller_token']['token'] is defined
      ansible.controller.job_list:
        status: successful
        query:
          playbook: "playbooks/ping.yml"
        aap_token: "{{ ansible_facts['controller_token']['token'] }}"
        controller_host: "{{ tower_host | default('http://127.0.0.1') }}"
        validate_certs: false