---

- name: Add host
  hosts: localhost
  tasks:
    - name: Add host to running inventory
      ansible.builtin.add_host:
        name: lollypop-container-key
        groups: all_vars
        ansible_host: 127.0.0.1
        ansible_connection: local

- name: Test
  hosts: all
  gather_facts: false
  tasks:
    - name: test
      delegate_to: lollypop-container-key
      ansible.builtin.command: echo hello