---
- name: azure_rm_resourcegroup_info EE run test
  hosts: localhost

  vars:
    az_name: ""
    sub_id: ""
  tasks:
    - name: run the info
      azure.azcollection.azure_rm_resourcegroup_info:
        name: "{{ az_name }}"
        subscription_id: "{{ sub_id }}"
      register: rg_info

    - debug: var=rg_info
