---

- name: Chatty Playbook (Generates Lots of Job Events)
  hosts: all
  gather_facts: false

  vars:
    number_of_messages: 1000

  tasks:
    - name: Talk to me
      loop: "{{ range(0, number_of_messages) | list }}"
      vars:
        chatty_message: "Hello Person #{{ item }}"
      ansible.builtin.debug:
        msg: "{{ chatty_message }}"
