---

- name: Cisco Test
  hosts: all

  tasks:
    # this will run the command 15 times
    - name: Run CLI Command
      loop: "{{ range(0, 15, 1) }}"
      ansible.netcommon.cli_command:
        command: show ip int br
