---

- name: Testing delegate_to task
  hosts: all
  gather_facts: true

  tasks:
    - name: Save current path for ANSIBLE_NET_SSH_KEYFILE
      ansible.builtin.set_fact:
        tmp_sshkeyfile: "{{ lookup('env', 'ANSIBLE_NET_SSH_KEYFILE') }}"

    - name: Test accessing keyfile from network credential
      ansible.builtin.command: cat /runner/env/{{ lookup('env', 'ANSIBLE_NET_SSH_KEYFILE') | basename }}
      delegate_to: localhost

      