---

- name: Testing delegate_to task
  hosts: all
  gather_facts: true

  tasks:
    - name: Printing out environment variables - no delegate_to
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]

    - name: Printing out environment variables - delegate_to
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      delegate_to: localhost

    - name: Save current path for ANSIBLE_NET_SSH_KEYFILE
      ansible.builtin.set_fact:
        tmp_sshkeyfile: "{{ lookup('env', 'ANSIBLE_NET_SSH_KEYFILE') }}"

    - name: Test accessing keyfile from network credential
      ansible.builtin.command: cat {{ lookup('env', 'ANSIBLE_NET_SSH_KEYFILE') }}
      delegate_to: localhost
      environment:
        ANSIBLE_NET_SSH_KEYFILE: "/runner/env/{{ tmp_sshkeyfile | basename }}"

      