---

- name: Debug VMware Credential
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Show credential
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - "{{ lookup('env', 'VMWARE_USER') }}"
