---

- name: Debug VMware Credential
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Create variable
      ansible.builtin.set_fact:
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        
    - name: Show credential
      ansible.builtin.debug:
        var: username
