---

- name: Delegate playbook
  hosts: localhost
  gather_facts: true

  vars:
    _delegate_to_host: "{{ delegate_to_host | default('localhost') }}"
    _delegate_facts: "{{ delegate_host_facts | default(false) }}"

  tasks:
    - name: Command run on the delegated host
      ansible.windows.win_shell: "Write-Host 'Hello'"
      delegate_to: "{{ _delegate_to_host }}"
      delegate_facts: "{{ _delegate_facts }}"
