---

- name: Docker Hello World
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Check if docker.sock file exists
      ansible.builtin.command: stat {{ item }}
      loop:
        - /var/run/docker.sock
        - /run/docker.sock
      ignore_errors: true
        
    - name: Run hello-world container
      community.docker.docker_container:
        name: hello_world
        image: hello-world
        auto_remove: true
        state: started
        docker_host: unix://run/docker.sock
