---

- name: Export Automation Controller Configuration
  hosts: all
  gather_facts: false

  tasks:
    - name: Export config
      ansible.controller.export:
        applications: 'all'
        credential_types: 'all'
        credentials: 'all'
        execution_environments: 'all'
        inventory_sources: 'all'
        job_templates : 'all'
        notification_templates: 'all'
        organizations: 'all'
        projects: 'all'
        schedules: 'all' 
        teams: 'all'
        users: 'all'
        workflow_job_templates: 'all'
      environment: "{{ auth_env }}"
      register: daily_export
      delegate_to: localhost
