---

- name: Playbook that fails
  hosts: all
  
  tasks:
    - ansible.builtin.ping:
  
    - ansible.builtin.fail:
      when: "{{ condition | default(true) }}"

    - ansible.builtin.command: sleep 30s
