---

- name: Playbook that fails
  hosts: all
  gather_facts: false

  vars:
    condition: true
  
  tasks:
    - ansible.builtin.fail:
      when: condition

    - ansible.builtin.command: sleep 30s
