---

- name: Testing ansible.builtin.fetch
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Fetch requested file
      ansible.builtin.fetch:
        src: "{{ filename }}"
        dest: /tmp/
        flat: true

    - name: List out file contents
      ansible.builtin.command: cat /tmp/{{ filename | basename }}
      delegate_to: localhost
