---

- name: Testing ansible.builtin.fetch
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Fetch requested file
      ansible.builtin.fetch:
        src: "{{ filename }}"
        dest: /tmp/
        flat: true

    - name: Copy file to Automation Controller
      delegate_to: "{{ copy_to_host }}"
      vars:
        ansible_user: "{{ username }}"
        ansible_password: "{{ password }}"
      ansible.builtin.copy:
        src: /tmp/{{ filename | basename }}
        dest: /tmp/{{ filename | basename }}
        mode: '0644'
