---

- name: Test
  hosts: all:!local
  gather_facts: false

  tasks:

    - name: Create a local directory and files
      delegate_to: localhost
      loop:
        - path: ./test_dir
          state: directory
        - path: ./test_dir/test1
          state: touch
        - path: ./test_dir/test2
          state: touch
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"

    # Here are two different methods to list out the files within

    - name: List out the files in ./test_dir
      delegate_to: localhost
      ansible.builtin.find:
        paths: ./test_dir

    - name: List out the files in ./test_dir
      delegate_to: localhost
      ansible.builtin.command: find ./test_dir

    - name: Sync the ./test_dir to /tmp on managed host
      ansible.builtin.copy:
        src: ./test_dir
        dest: /tmp
