---

- name: Test
  hosts: all
  gather_facts: false
  strategy: "{{ strategy | default('linear') }}"

  handlers:
    - name: HANDLER
      changed_when: true
      ansible.builtin.debug:
        msg: "HANDLER"

  tasks:
    - name: TASK
      notify: HANDLER
      changed_when: inventory_hostname == "localhost2"
      ansible.builtin.debug:
        msg: "TASK"

    - name: GOOD TASK
      run_once: true
      changed_when: false
      ansible.builtin.command: echo hello

  post_tasks:
    - name: POST_TASK
      ansible.builtin.debug:
        msg: "POST_TASK"
