---

# this file will be used with job slicing set to > 1
- name: job-slice-1
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:
    - name: Create and populate variable name
      loop: "{{ groups['all'] }}"
      ansible.builtin.set_fact:
        vmware_hosts: "{{ vmware_hosts | default({}) | combine({ 
          (hostvars[item].name): {
            'name': hostvars[item].name
          }
        }) }}"

    - name: Set stats on new variable
      ansible.builtin.set_stats:
        data:
          vmware_data: "{{ vmware_hosts }}"
