---

# this file will be used with job slicing set to > 1
- name: job-slice-1
  hosts: all
  gather_facts: false

  tasks:
    - name: Create and populate variable name
      loop: "{{ groups['all'] }}"
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_stats:
        per_host: true
        data:
          vmware_data: 
            name: "{{ hostvars[item].inventory_hostname }}"
