---

# this file will display the data from job-slice-1.yml

- name: Display data
  hosts: all
  gather_facts: false
  tasks:
    - name: Display data
      ansible.builtin.debug: var=hostvars[inventory_hostname].vmware_data
