---

# this file will be used with job slicing set to > 1
- name: job-slice-1
  hosts: all
  gather_facts: false

  tasks:
    - name: Create and populate variable name
      delegate_to: localhost
      ansible.builtin.set_fact:
        cacheable: true
        vmware_data: 
          name: "{{ inventory_hostname }}"
