---

- name: Run some kubernetes tasks
  hosts: all
  gather_facts: "{{ gather_facts | default(False) }}"

  tasks:

    - name: Get k8s cluster info
      kubernetes.core.k8s_cluster_info:
        username: "{{ username | default(omit) }}"
        password: "{{ username | default(omit) }}"