---

- name: Check various uses of needs-restarting
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'

    - name: Calling needs-restarting
      block:
        - name: Check the environment variables when executing needs-restarting
          ignore_errors: true
          ansible.builtin.shell: |
            set -o pipefail
            env
            needs-restarting -r

        - name: Pass in the PATH environment variable
          ignore_errors: true
          environment:
            PATH: "{{ ansible_facts['env']['PATH'] }}:/usr/bin"
          ansible.builtin.shell: |
            set -o pipefail
            env
            needs-restarting -r

    - name: Calling dnf
      block:
        - name: Check the environment variables when executing dnf needs-restarting
          ignore_errors: true
          ansible.builtin.shell: |
            set -o pipefail
            env
            dnf needs-restarting -r

        - name: Pass in the PATH environment variable
          ignore_errors: true
          environment:
            PATH: "{{ ansible_facts['env']['PATH'] }}:/usr/bin"
          ansible.builtin.shell: |
            set -o pipefail
            env
            dnf needs-restarting -r

    - name: Call bash -lc
      block:
        - name: Check the environment variables when executing bash -lc 'needs-restarting'
          ignore_errors: true
          ansible.builtin.shell: |
            set -o pipefail
            env
            bash -lc "needs-restarting -r"

        - name: Pass in the PATH environment variable
          ignore_errors: true
          environment:
            PATH: "{{ ansible_facts['env']['PATH'] }}:/usr/bin"
          ansible.builtin.shell: |
            set -o pipefail
            env
            bash -lc "needs-restarting -r"
