---

- name: Print OpenSSL Certs in a Openshift environment for AAP
  hosts: localhost
  connection: local
  
  tasks:
    - name: Get extract directory
      ansible.builtin.command: find /etc/pki
    
    - name: Cat out bundle-ca
      ansible.builtin.shell: find /etc/pki/ca-trust/source/anchors -type f -exec cat {} \;
      ignore_errors: true
    
    - name: Search for red hat in trust list
      ansible.builtin.shell: |
        trust list | grep -i 'red hat'
