---

- name: Display Package Data
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather Facts
      timeout: 20
      ansible.builtin.setup:

    - name: Get Package Data
      ansible.builtin.package_facts:

    - name: Display Packages
      ignore_errors: true
      ansible.builtin.debug:
        var: "{{ hostvars[inventory_hostname]['packages'] }}"
