---

- name: Ping Playbook with Pause
  hosts: all

  tasks:
    - name: Block
      block:
        - name: Connect to server
          ignore_errors: true
          ansible.builtin.ping:
      always:
        - name: Pause for debugging
          ansible.builtin.pause:
            seconds: 300
