---

- name: Print Variables
  hosts: all
  gather_facts: false

  vars:
    variable_to_print: "{{ input_var | list }}"

  tasks:
    - name: Print large integer (without filter)
      loop: "{{ variable_to_print }}"
      ansible.builtin.debug:
        msg: "{{ item }}"

    - name: Print large integer (with filter)
      loop: "{{ variable_to_print }}"
      ansible.builtin.debug:
        msg: "{{ item | int }}"
