---

- name: Print host variables
  hosts: all
  serial: 1
  run_once: true
  tasks:
    - name: Print host vars
      ansible.builtin.debug: var=hostvars[inventory_hostname]
      ignore_errors: true
      
    - name: Print vars
      ansible.builtin.debug: var=vars
      ignore_errors: true
