---

- name: Random Failure of One Host
  hosts: all
  gather_facts: true

  tasks:
    - name: Generate array of numbers
      no_log: true
      run_once: true
      loop: "{{ range(0, play_hosts|length, 1) | list }}"
      ansible.builtin.set_fact:
        host_count: "{{ host_count | default([]) + [item | int] }}"

    - name: Pick host index
      run_once: true
      no_log: true
      ansible.builtin.set_fact:
        host_idx: "{{ host_count | ansible.builtin.random }}"

    - name: Debug play_hosts variable
      ansible.builtin.debug:
        var: play_hosts
        verbosity: 3

    - name: Debug host index
      ansible.builtin.debug:
        var: host_idx
        verbosity: 3

    - name: Fail on one random host
      when: inventory_hostname == play_hosts[host_idx|int]
      ansible.builtin.fail:
        msg: "{{ inventory_hostname }} was picked to fail"