---

- name: Rebooting Host with a Handler
  hosts: all
  become: true
  become_user: root
  
  tasks:
    - name: reboot host
      ansible.builtin.reboot:
        reboot_timeout: "{{ pb_ansible_timeout | default(15) }}"
