---

- name: Rebooting Host with a Handler
  hosts: all
  become: true
  become_user: root
  
  handlers:
    - name: reboot host
      ansible.builtin.reboot:
        reboot_timeout: 15
  
  tasks:
    - name: Task to trigger a handler
      ansible.builtin.debug:
        msg: "Need to reboot host now!!!! Get to the choppa!"
      notify: reboot host
