---

- name: Export variables via set_stats
  hosts: all
  gather_facts: false
  tasks:
    - name: Export following variables
      ansible.builtin.set_stats:
        data:
          variable_1: "HOORAY FOR VARIABLE 1"
          variable_2: "HOORAY FOR VARIABLE 2"
