---

- name: Set Facts with cacheable
  hosts: all
  gather_facts: true

  tasks:
    - name: Use dig to lookup the FQDN
      ansible.builtin.set_fact:
        variable_1: '123'
        cacheable: true
