---

- name: Export variables via set_stats
  hosts: all
  gather_facts: false

  vars:
    cs_variable_1: "{{ variable_1 | default('NO VARIABLE 1') }}"
    cs_variable_2: "{{ variable_2 | default('NO VARIABLE 2') }}"

  tasks:
    - name: Display Variable 1
      ansible.builtin.debug:
        var: cs_variable_1

    - name: Display Variable 2
      ansible.builtin.debug:
        var: cs_variable_2