---

- name: Playbook that skips
  hosts: all
  gather_facts: false
  
  vars:
    skip_value: 0
    _loop_count: "{{ loop_count | default(10) }}"
  
  tasks:
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0    
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0    
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0    
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0    
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0
    - name: Skip this
      ansible.builtin.command: echo hello
      when: skip_value > 0          
    #- name: Skip this
    #  ansible.builtin.include_tasks: skip-task.yml
    #  with_sequence: start=0 end={{ _loop_count }}
