---

# terrible name for a file
- name: Slurp file and set to variable
  hosts: all
  tasks:
  
    - ansible.builtin.slurp:
        src: /etc/os-release
      register: var1
      
    - ansible.builtin.command: echo {{ var1.source }}
  
