---

- name: Playbook with tasks and timeouts
  hosts: all
  gather_facts: false

  tasks:
    - name: "Task with no timeout"
      ansible.builtin.command: echo "Hello"

    - name: "Task with timeout"
      timeout: "{{ task_timeout | default(2) }}"
      ansible.builtin.command: sleep 10s
