---

- name: Test
  hosts: all
  gather_facts: false

  tasks:
    - name: Install ps
      ansible.builtin.package:
        name: procps-ng
        
    - name: Run commands
      delegate_to: localhost
      ansible.builtin.shell: "{{ item }}"
      loop:
        - ssh -v cloud-user@{{ some_host | default('127.0.0.1') }}
        - env
        - ps faux
