---

- name: Write File to Directory
  hosts: all
  tasks:
    - name: Make sure directory exists
      ansible.builtin.set_fact:
        _wto_directory: "{{ directory | mandatory }}"
        
    - name: Write File
      ansible.builtin.lineinfile:
        path: "{{ _wto_directory }}/famous-line.txt"
        line: "It's just a flesh wound."
        state: 0644
        create: true
